# Generated by Django 4.1.5 on 2023-01-26 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("treemenuapp", "0002_menu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="topics",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="menu",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu",
                to="treemenuapp.menu",
            ),
        ),
    ]
