# Generated by Django 4.1.5 on 2023-01-26 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("treemenuapp", "0003_remove_menu_topics_menuitem_menu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu",
                to="treemenuapp.menu",
            ),
        ),
    ]
