# Generated by Django 4.1.5 on 2023-01-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treemenuapp", "0004_alter_menuitem_menu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="slug",
            field=models.SlugField(max_length=100, unique=True, verbose_name="url"),
        ),
    ]
